# Generated by Django 3.0.1 on 2019-12-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='items',
            new_name='item',
        ),
    ]
