# Generated by Django 3.0.1 on 2020-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200125_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
